### ISSUE TITLE
Image is attached to campaign that is sent as plain text

### ISSUE THREAD

**Issue by bramley** [arnoldle/phplist-plugin-inlineImagePlugin#3]
Created a campaign with an inline image. 
When the campaign was sent to a subscriber who is set to receive plain text format emails the email that was received had the inline image as an attachment.

![attached image](https://cloud.githubusercontent.com/assets/3147688/8704892/e9c3b23e-2b1d-11e5-8b62-6898d05a1e63.png)

**Comment by bramley** [comment]
A similar problem that looks to be related. The campaign report email sent to the admin also had the image attached

![screenshot from 2015-07-17 11 08 59](https://cloud.githubusercontent.com/assets/3147688/8745116/773e5db0-2c74-11e5-95b3-ba587c9e3539.png)

**Comment by arnoldle** [comment]
From Kechikan, Alaska:

OK, thanks. I'll look into it home. We'll be Thursday. Have had no internet till here. 

A.
