### ISSUE TITLE
Verifying result of file_get_contents()

### ISSUE THREAD

**Issue by bramley** [arnoldle/phplist-plugin-inlineImagePlugin#4]
The processing seems to distinguish between processing the queue and forwarding a message. There is also another scenario, which is sending a test message. The processing seems to treat this as forwarding a message but there is a problem handling an incorrect image url.

In method allowMessageToBeQueued() the call to file_get_contents() tests the result for failure. 
The same processing in method messageQueued() doesn't check the result, which means that the problem is not reported.

**Comment by arnoldle** [comment]
Thanks, Duncan, for these reports. I'm in Alaska right now & far from my computer. I will be home in 8 days and will look at this issue then. 

I'll also look at the issue of indicating in a text message where the inline image was removed from. AFAIK you can't display an inline image in a plain text message.

I'll prepare updates after I get home.

Thanks again. I'll get back to you once I'm home.

Arnold
